### ISSUE TITLE
Strcmp routine result is wrong 

### ISSUE THREAD

**Issue by xer0times** [quarkslab/tritondse#14]
Hi @RobinDavid 

Do you know why this line incremented by one (+1)? I removed it because my tests were producing incorrect values!

https://github.com/quarkslab/tritondse/blob/9805288a9f97c7085f230c0f40d8b670cbd09d6a/tritondse/routines.py#L1668

**Comment by xer0days** [comment]
Test source is like issue #12 . I changed one of the `strstr` functions to `strcmp` and got the wrong value in the return register. It's different when you get it from concrete execution.

There's one `strcmp` in the source.

**Comment by RobinDavid** [comment]
Ok thanks! We will reuse your sample to fix it.

**Comment by cnheitman** [comment]
Hi! Commit 22ee7274c790ee93623e01f6e1dbc6af734b3378 should fix this.
