### ISSUE TITLE
getchar routine does not work

### ISSUE THREAD

**Issue by llaubin** [quarkslab/tritondse#20]
Hi ! the hook provided for `getchar` (see [rtn_getchar](https://github.com/quarkslab/tritondse/blob/main/tritondse/routines.py#L1356)) does not work and returns the following error :

```
can't call inject_symbolic_file_register with regsiter larger than 1!
```

Internally, this hook calls `inject_symbolic_file_register` (cf https://github.com/quarkslab/tritondse/blob/main/tritondse/symbolic_executor.py#L805), which makes an invalid check on the register size :
```
  if reg.getSize != 1:
      logger.error("can't call inject_symbolic_file_register with regsiter larger than 1!")
      return
```

There are two problems with this test:
- the missing `()`  😄 
- The `reg` argument, which can be either a `str` or a `Register`, does not have a `getSize()` method if its type is `str`.

Moreover, `inject_symbolic_file_register` is called with `pstate.return_register`, which on a x64 binary will be `RAX`, so `reg.getSize()` will return 8. 

Please also keep in mind that `getchar` either returns a 8 bits value, or `EOF=-1` in case of an error. Which means a 32 or 64 bits value depending of the architecture. Symbolizing only `AL` could be bring some side effects (or a nice trick to detect the emulation 😁  )

**Comment by cnheitman** [comment]
Thanks @llaubin for reporting the issue o/ PR #26 should have fixed this issue.
