### ISSUE TITLE
Example error loading lief elf

### ISSUE THREAD

**Issue by coolkingcole** [quarkslab/tritondse#21]
I was trying to run the examples from [here](https://blog.quarkslab.com/introducing-tritondse-a-framework-for-dynamic-symbolic-execution-in-python.html) in an ubuntu:latest docker and get a traceback trying to load lief.

Running the code under-"To automatically solve this crackme, we use the following script:"

```
root@074cb66a7031:/# python3 example.py 
Traceback (most recent call last):
  File "//example.py", line 3, in <module>
    from tritondse import CompositeData
  File "/usr/local/lib/python3.10/dist-packages/tritondse/__init__.py", line 2, in <module>
    from .loaders.program       import Program
  File "/usr/local/lib/python3.10/dist-packages/tritondse/loaders/__init__.py", line 3, in <module>
    from .program import Program
  File "/usr/local/lib/python3.10/dist-packages/tritondse/loaders/program.py", line 25, in <module>
    lief.EXE_FORMATS.ELF: Platform.LINUX,
AttributeError: module 'lief' has no attribute 'EXE_FORMATS'
```

I think this is probably just a version mismatch problem, but thought I would make an issue in case anyone else runs into the issue.

**Comment by cnheitman** [comment]
Hi! Indeed, there is an issue with LIEF `0.14.*`. We'll fix this soon. For now, try LIEF `v0.13.2`, it should work fine with that version.

**Comment by cnheitman** [comment]
Hi! We upgrade to LIEF v0.14.0 so this shouldn't be an issue anymore.

I'm closing this, please re-open if you have a related issue.
