### ISSUE TITLE
'tritondse' has no attribute 'logging'

### ISSUE THREAD

**Issue by Defend2505** [quarkslab/tritondse#22]
I have an issue with "import tritondse" when I use ipython
AttributeError: partially initialized module 'tritondse' has no attribute 'logging' (most likely due to a circular import)

**Comment by RobinDavid** [comment]
We have few issues currently being fixed, but I never got this. Could elaborate on:

* Python version
* Tritondse version (pip package, or main branch ?)

**Comment by cnheitman** [comment]
Hi! Is this still an issue? @Defend2505 Could you try the lastest version (`v0.1.11`) and check whether the problem persists?
