### ISSUE TITLE
Memory violation: (Perm.R: 0x10000008 unmapped) during exploration

### ISSUE THREAD

**Issue by ochekanin** [quarkslab/tritondse#31]
Hello,

I'm trying to use tritondse with my binary and corpus of seed files for exploration purpose.

Unfortunately I got an error 'Memory violation: (Perm.R: 0x10000008 unmapped)' each time. I printed instruction in trouble and it's always the same (268435464 if it makes sense).

Below is how I run tritondse. I put corpus in worklist as mentioned in guide but it expects them to have .cov at the end.
Am I right that storing seed files in worklist/ dir is correct way to pass data via stdin?

Could you please help me to identify the issue.

```
from tritondse import Config, Seed, Program, ProcessState, CompositeData, \
     SymbolicExplorator, BranchSolvingStrategy, SeedFormat, Loader

config = Config(
    pipe_stdout=True,
    pipe_stderr=True,
    # memory_segmentation=False,
    workspace="..."
)

bin = Program("my-app")

dse = SymbolicExplorator(config, bin)
dse.explore()
```

**Comment by cnheitman** [comment]
Hi! Sorry for the late response.

You should provide the seeds in the following way:

```python
bin = Program("my-app")

dse = SymbolicExplorator(config, bin)

for seed_file in os.listdir(SEED_DIR):
    dse.add_input_seed(Seed.from_file(f"{SEED_DIR}/{seed_file}"))

dse.explore()
```

**Comment by cnheitman** [comment]
I'm closing this issue, please re-open if you want to discuss the issue in more detail.

**Comment by ochekanin** [comment]
@cnheitman thank you for answer and support
