### ISSUE TITLE
Problems installing on MacOS

### ISSUE THREAD

**Issue by JJK96** [quarkslab/tritondse#5]
I installed triton using the instructions on the Triton github page:

https://github.com/jonathansalwan/Triton#linux-and-macos

I test that triton is indeed installed:

```
$ python
Python 3.11.3 (main, Apr  7 2023, 19:25:52) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import triton
>>>
```

Then I install tritondse:

```
$ pip install tritondse
Collecting tritondse
  Using cached tritondse-0.1.3-py3-none-any.whl (107 kB)
  Using cached tritondse-0.1.2-py3-none-any.whl (106 kB)
  Using cached tritondse-0.1.1.tar.gz (93 kB)
  Preparing metadata (setup.py) ... done
ERROR: Cannot install tritondse==0.1.1, tritondse==0.1.2 and tritondse==0.1.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    tritondse 0.1.3 depends on triton-library
    tritondse 0.1.2 depends on triton-library
    tritondse 0.1.1 depends on triton-library

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

It seems that it searches for triton-library, which is not installed when installing triton from github.

**Comment by RobinDavid** [comment]
Hello @JJK96.

Yes if you installed triton manually, when trying to install tritondse it will try fetching it on Pypi as it has no way to know it is already installed.
As triton is not packaged for MacOS on Pypi.

The simplest option is to git clone tritondse, then removing ```triton-library``` from the requirements of the `setup.py` and then doing ```pip install .```.

Let us know if it worked, it should..

*(please keep in mind it has not been tested on macOS)*

**Comment by JJK96** [comment]
Yeah, I already did that, that works. But maybe it's still good to put this in the docs somewhere

**Comment by RobinDavid** [comment]
Yes will do.
