### ISSUE TITLE
replacing a function with a callback

### ISSUE THREAD

**Issue by liordror** [quarkslab/tritondse#6]
me and my partner have noticed that using the function register_function_callback doesn't replace the function but performs the callback prior to the hooked function.
is there any way we are able to replace the function completely with our callback?

**Comment by liordror** [comment]
First, thanks for answering!
Our case is case 1. 
We want to hook the functions send, recv, connect, listen, socket, etc.. But it seems as if they are not supported by the system as imported functions, we get the error: 
symbol socket imported but unsupported.

How can we overcome this problem?

**Comment by RobinDavid** [comment]
Ok, thus if you are using the `Program`, you need to implement the various stubs associated to these functions. Thus you need to implement this kind of snippet:

```python
def recv_routine(se: 'SymbolicExecutor', pstate: 'ProcessState'):
    # Implement the stub
    return ...  # you need to return a value

# Then on the SymbolicExplorator
explorator.cbm.register_pre_imported_routine_callback("recv", recv_routine)
# same for the other callbacks
```

By doing that your callback will be called whenever the function is called.
You can look at the other [routines](https://github.com/quarkslab/tritondse/blob/main/tritondse/routines.py) to see how we implemented the executed routines.

If you implement interesting routines, feel free to do a PR ;)

**Comment by carolynsala585** [comment]
Hi @RobinDavid ,

Is there anything we should do if we're using `CleLoader` ?

**Comment by RobinDavid** [comment]
@carolynsala585 as explained above there are two scenarios depending on the loader you are using.

### Case 1: using ``Program`` loader

With this loader, only the main ELF binary is loaded. In this case only a subset of imported functions are supported  (``SUPPORTED_ROUTINES``) list. You're right in this scenario we support `getenv` but not `socket`. One can implement a stub and register it with `register_pre_imported_routine_callback`.

### Case 2: Using ``CleLoader`` loader

With this loader, all shared libraries will recursively loaded, and imports resolved. Thus in this case there are no longer imported functions but just function. If you want to hook one you have to use: ``register_function_callback``.

---
The exact behavior depending on the loader change, and I agree it is not absolutely clear.
I will show you how to solve your snippet of the other issue.
