### ISSUE TITLE
searching bar

### ISSUE THREAD

**Issue by liordror** [quarkslab/tritondse#7]
the searching bar in the API does not work, it would be lovely if we could search for specific things because right now it is very difficult to search the whole website and source code for information. it would give us a better understanding of tritondse and make our work easier.

**Comment by RobinDavid** [comment]
Do you mean the search bar, at the top-left here: https://quarkslab.github.io/tritondse/index.html  ?
It works well on my side.
Have you some javascript blocker or something similar enabled in your browser ?
